# Generated by Django 2.2 on 2019-10-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color_int',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.FloatField(blank=True, choices=[('Disponible', 'Disponible'), ('Apartado', 'Apartado')], null=True),
        ),
    ]
