# Generated by Django 2.2 on 2019-11-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kilometrajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_ini', models.IntegerField()),
                ('k_fin', models.IntegerField()),
                ('ano2019', models.CharField(max_length=100)),
                ('ano2018', models.CharField(max_length=100)),
                ('ano2017', models.CharField(max_length=100)),
                ('ano2016', models.CharField(max_length=100)),
                ('ano2015', models.CharField(max_length=100)),
                ('ano2014', models.CharField(max_length=100)),
                ('ano2013', models.CharField(max_length=100)),
                ('ano2012', models.CharField(max_length=100)),
                ('ano2011', models.CharField(max_length=100)),
                ('ano2010', models.CharField(max_length=100)),
            ],
        ),
    ]
