# Generated by Django 2.2 on 2019-11-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_kilometrajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONSECUTIVO', models.CharField(max_length=100)),
                ('MARCA', models.CharField(max_length=100)),
                ('NUEVO_USADO', models.CharField(max_length=100)),
                ('ANO_MODELO', models.CharField(max_length=100)),
                ('FORMULA', models.CharField(max_length=100)),
                ('SUBMARCA', models.CharField(max_length=100)),
                ('VERSIÓN', models.CharField(max_length=100)),
                ('PRECIO_VENTA', models.CharField(max_length=100)),
                ('PRECIO_COMPRA', models.CharField(max_length=100)),
                ('TIPO', models.CharField(max_length=100)),
                ('PRECIO_INTERMEDIO', models.CharField(max_length=100)),
                ('PRECIO_AGENCIA_CERTIFICADOS', models.CharField(max_length=100)),
                ('ALGO', models.CharField(max_length=100)),
                ('PRECIO_HABOLT', models.CharField(max_length=100)),
                ('CONSIGNA', models.CharField(max_length=100)),
                ('PRÉSTAMO', models.CharField(max_length=100)),
            ],
        ),
    ]
