# Generated by Django 2.2 on 2019-11-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_carros'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='TREINTA_DIAS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
