# Generated by Django 2.2 on 2019-11-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carros_treinta_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2010',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2011',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2012',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2013',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2014',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2015',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2016',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2017',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2018',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kilometrajes',
            name='ano2019',
            field=models.IntegerField(),
        ),
    ]
