# Generated by Django 2.2 on 2019-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191103_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=500)),
                ('eleccion', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('extra1', models.CharField(blank=True, max_length=100, null=True)),
                ('extra2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
