# Generated by Django 2.2 on 2019-11-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191109_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='eleccion',
            field=models.CharField(max_length=200),
        ),
    ]
