# Generated by Django 2.2 on 2019-11-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191126_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='km',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='marca',
            field=models.CharField(choices=[('Acura', 'Acura'), ('Audi', 'Audi'), ('BAIC', 'BAIC'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('JAC', 'JAC'), ('JAC Comerciales', 'JAC Comerciales'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Land Rover', 'Land Rover'), ('Lincoln', 'Lincoln'), ('Mazda', 'Mazda'), ('Mini', 'Mini'), ('Mitsubishi', 'Mitsubishi'), ('Nissan ', 'Nissan '), ('Nissan Comerciales', 'Nissan Comerciales'), ('Peugeot', 'Peugeot'), ('Peugeot Comerciales', 'Peugeot Comerciales'), ('Porsche', 'Porsche'), ('Ram Dodge Comerciales', 'Ram Dodge Comerciales'), ('Renault', 'Renault'), ('Seat', 'Seat'), ('Suzuki', 'Suzuki'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatch Back', 'Hatch Back'), ('Pick-Up', 'Pick-Up'), ('Minivan', 'Minivan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
