# Generated by Django 2.2 on 2019-11-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191126_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='check',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leads',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'Disponible'), ('S', 'Apartado'), ('D', 'otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatch Back', 'Hatch Back'), ('Pick-Up', 'Pick-Up'), ('Minivan', 'Minivan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('4x4', '4x4'), ('Convertible', 'Convertible'), ('Electrico', 'Electrico')], max_length=100),
        ),
    ]
